/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jrdcom_com_jnidemo_HelloJni */

#ifndef _Included_jrdcom_com_jnidemo_HelloJni
#define _Included_jrdcom_com_jnidemo_HelloJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jrdcom_com_jnidemo_HelloJni
 * Method:    stringFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jrdcom_com_jnidemo_HelloJni_stringFromJni
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
